extend:
  initializr:
    architectures:
      - id: "none"
        name: "None"
        default: true
      - id : "mvc"
        name: "MVC"
        default: false
        facets:
          - "web"
          - "thymeleaf"
          - "h2"
          - "jpa"
      - id: "microservice"
        name: "Microservice"
        default: false
        facets:
          - "web"
          - "jpa"
    oauthapps:
      github:
        enabled: true
        clientid: ${kv-github-client-id}
        clientSecret: ${kv-github-client-secret}
        oauthUri: https://github.com/login/oauth/authorize
        redirectUri: ${kv-github-client-redirectUri}

spring:
  cloud:
    azure:
      keyvault:
        secret:
          # set property-source-enabled to `true` if you want to use keyvault
          property-source-enabled: false
          property-sources:
            - name: key-vault-property-souece
              endpoint: ${input-your-keyvault-endpoint}
