extend:
  initializr:
    architectures:
      - id: "none"
        name: "None"
        default: true
      - id : "mvc"
        name: "MVC"
        default: false
        facets:
          - "web"
          - "thymeleaf"
          - "h2"
          - "jpa"
      - id: "microservice"
        name: "Microservice"
        default: false
        facets:
          - "web"
          - "jpa"
    connectors:
        github:
          enabled: true
          clientid: 1b17c66d923a18bc63c0
          oauthUri: https://github.com/login/oauth/authorize
          # temp oauth app clientSecret
          clientSecret: b018a170f676d4fc332635051f670bdbbd0a225b
          redirectUri: http://localhost:8080/login/oauth2/code/github
        bitbucket:
          enable: false

