extend:
  initializr:
    architectures:
      - id: "none"
        name: "None"
        default: true
      - id : "mvc"
        name: "MVC"
        default: false
        facets:
          - "web"
          - "thymeleaf"
          - "h2"
          - "jpa"
      - id: "microservice"
        name: "Microservice"
        default: false
        facets:
          - "web"
          - "jpa"
    connectors:
      - type: github
        clientid: 1b17c66d923a18bc63c0
        oauthUri: https://github.com/login/oauth/authorize?redirect_uri=http://localhost:8080/login/oauth2/code/github&client_id=1b17c66d923a18bc63c0